[package]
name = "icy_board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icy_ppe = { path="../PPLEngine/icy_ppe" }
icy_board_engine = { path="../PPLEngine/icy_board_engine" }

lazy_static = "1.4.0"
clap = { version="4.5.2", features = ["derive"] }
semver = "1.0.20"
thiserror = "1.0.57"
ariadne = "0.4.0"
unicase = "2.7.0"
byteorder = "1.5.0"
log = "0.4.21"
ratatui = "0.26.1"
crossterm = "0.27.0"
chrono = "0.4.37"
qfile = "3.0.1"
easy_reader = "0.5.2"
substring = "1.4.5"

[profile.release]
strip = "symbols"