[package]
name = "icy_board_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icy_engine = { workspace = true }
icy_net = { workspace = true }
codepages = { workspace = true }

lazy_static = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
crossterm = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
semver = { workspace = true }

unicase = { workspace = true }
rand = { workspace = true }

async-recursion = "1.1.0"
radix_fmt = "1"
qfile = "3.0.1"
substring = { workspace = true }
byteorder = "1.5.0"
strum = { workspace = true }
strum_macros = "0.26.2"
toml = { workspace = true }
async-trait = "0.1.80"
# interpreter deps
[dev-dependencies]
stopwatch = "0.0.7"

