[package]
name = "icy_board_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icy_engine = { workspace = true }
icy_net = { workspace = true }
icy_parser_core =  { workspace = true }
icy_sixel = { workspace = true }
image = { workspace = true }
jxl-oxide = { workspace = true }
zune-jpegxl = { workspace = true }
zune-core = { workspace = true }
codepages = { workspace = true }

lazy_static = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
dizbase = { workspace = true}
crossterm = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_with = "3.8.1"
tokio = { workspace = true }
semver = { workspace = true }
regex = { workspace = true }
walkdir = { workspace = true }
bitflag = { workspace = true }
tempfile = { workspace = true }

unicase = { workspace = true }
fastrand = { workspace = true }
jamjam = { workspace = true }
bstr = { workspace = true }

strum = { workspace = true }
strum_macros = { workspace = true }
serde-inline-default = "1.0.0"

async-recursion =  { workspace = true }
radix_fmt = "1"
byteorder = "1.5.0"
toml = { workspace = true }
async-trait =  { workspace = true }
logos = "0.16.1"
humanize-bytes = "1.0.5"
reqwest = { version = "0.13", features = ["json", "blocking"] }
md5 = "0.8.0"
temp-file = "0.2.0"
glob = "0.3.2"
chumsky = "0.13.0"
creditcard = "0.1.0"
zip = { workspace = true }
argon2 = "0.5.3"
# argon2 re-exports OsRng, but only if someone asks rand_core for it.
rand_core = { version = "0.6", features = ["getrandom"] }
bcrypt = "0.19.3"
fs4 = "1"
base64 = "0.22.1"
sha2 = "0.10.9"

# interpreter deps
[dev-dependencies]
pretty_assertions = "1"
stopwatch = "0.0.7"

[target.'cfg(not(windows))'.dependencies]
# termion is not supported on Windows
termion = { version = "4.0.0", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
