[package]
name = "pplc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["artwork"]
artwork = ["dep:icy_engine"]

[build-dependencies]
icy_board_buildinfo = { workspace = true }

[dependencies]
codepages = { workspace = true }
icy_engine = { workspace = true, optional = true }
icy_board_ppl = { workspace = true }

lazy_static = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
icy_board_cli = { workspace = true }
crossterm = { workspace = true }

ariadne = { workspace = true }
unicase = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
diff = "0.1.13"

[dev-dependencies]
tempfile = { workspace = true }
