name = "PPL"
grammar = "ppl"
path_suffixes = ["pps", "ppd", "ppx"]
line_comments = ["; "]
autoclose_before = ";:.,=}])>"
tab_size = 4
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
