name = "SYSOP"
security_level = 255
exp_date = 0000-01-01
exp_security_level = 0
protocol = "Z"
page_len = 0
date_last_dir_read = "1970-01-01T00:00:00Z"
chat_status = "Available"
conference_flags = ""

[password]
password = ""
last_change = "1970-01-01T00:00:00Z"
expire_date = "1970-01-01T00:00:00Z"

[flags]
fse_mode = "Yes"

[stats]
first_date_on = "1970-01-01T00:00:00Z"
last_on = "2025-03-02T07:49:39.410407390Z"
num_times_on = 1
