name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4   
    - name: Check formatting
      run: |
        rustup  update
        cargo fmt --all -- --check
    - run: rustup component add clippy
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgtk-3-dev libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests
      run: |
        cargo test --all-features